### ISSUE TITLE
surrealdb.js@1.0.0-beta.5 error

### ISSUE THREAD

**Issue by gtwww** [dvanmali/surrealdb-nuxt-starter#3]
A very useful project. It works fine under `surrealdb.js@0.11.1`, but it's not compatible with the latest `surrealdb.js@1.0.0-beta.5`. The error message is as follows:

```shell
dev:  ERROR  [nitro] [unhandledRejection] There is no connection available at this moment.
dev:
dev:   at HttpEngine.rpc (node_modules/.pnpm/surrealdb.js@1.0.0-beta.5/node_modules/surrealdb.js/src/library/engine.ts:315:10)
dev:   at runNextTicks (node:internal/process/task_queues:60:5)
dev:   at listOnTimeout (node:internal/timers:540:9)
dev:   at process.processTimers (node:internal/timers:514:7)
dev:   at Surreal.ping (node_modules/.pnpm/surrealdb.js@1.0.0-beta.5/node_modules/surrealdb.js/src/surreal.ts:160:21)

dev:  ERROR  [nitro] [unhandledRejection] There is no connection available at this moment.
dev:
dev:   at HttpEngine.rpc (node_modules/.pnpm/surrealdb.js@1.0.0-beta.5/node_modules/surrealdb.js/src/library/engine.ts:315:10)
dev:   at Surreal.ping (node_modules/.pnpm/surrealdb.js@1.0.0-beta.5/node_modules/surrealdb.js/src/surreal.ts:160:21)
```

I'm not sure if it's a compatibility issue with other dependencies.

**Comment by dvanmali** [comment]
Thanks for raising this issue @gtwww! It appears that surreal.js version 1 operates via websockets instead of the http rpc endpoint. To fix this, change the runtime configuration to `surrealUrl: 'ws://localhost:8000'` located inside the nuxt.config.ts. I put up a branch with this fix for you and initiated a Draft pull request. I will merge once the javascript library leaves beta. Let me know if this works.

**Comment by gtwww** [comment]
@dvanmali After following your instructions and making the modifications, everything is working perfectly now. Thank you very, very much!
